apiVersion: v1
kind: Service
metadata:
  name: java-app-loadbalancer
  namespace: hk
  annotations:
    # ESSENCIAL para ser gratuito
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
spec:
  type: LoadBalancer  # Isso cria o LB público
  ports:
    - name: http
      port: 80          # Porta pública do LB
      targetPort: 8080  # DEVE bater com containerPort do seu deployment
  selector:
    app: java-app     # DEVE ser IDÊNTICO ao label do seu deployment